compile:

server1: 
	python3 -u server.py 1

server2: 
	python3 -u server.py 2

server3: 	
	python3 -u server.py 3

server4: 	
	python3 -u server.py 4

server5: 	
	python3 -u server.py 5

clean:
	rm -fr __pycache__
	rm -f *.txt
	clear

diskclean:
	rm -f *.txt

cleandisk:
	rm -f *.txt